name: Deploy to titanweb.vn website.
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: git-ftp-action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.URL }}
          ftp-username: ${{ secrets.USER }}
          ftp-password: ${{ secrets.PASSWORD }}
          server-dir: ${{secrets.DIR}}
          exclude:
          - "**/.git*"
          - "**/.git*/**"
          - "**/node_modules/**"
          - "fileToExclude.txt"
