name: Deploy to small-js.
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@master
      - name: git-ftp-action
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.URL }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          server-dir: ${{secrets.DIR}}
          exclude: '**/.git* **/.git*/** **/node_modules/** fileToExclude.txt'
